[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "N"]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true

[project]
name = "image-dup-search"
version = "0.0.0"
descriprion = "Система поиска дубликатов изображений с использованием методов компьютерного зрения"
readme = "README.md"
authors = [
	{ name = "Kazuma", email = "hmelevski_1948@mail.ru" }
]
dependencies = ["pillow", "imagehash", "numpy"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"



[project.optional-dependencies]
dev = ["pytest>=8.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
target-version = ["py312"]
